# Generated by Django 3.2.14 on 2024-01-28 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('blog_date', models.DateTimeField(blank=True, default=datetime.date, null=True)),
            ],
        ),
    ]
