# Generated by Django 3.2.14 on 2024-01-28 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blog_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
    ]
