# Generated by Django 3.2.14 on 2024-01-28 06:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_date',
            field=models.CharField(default=datetime.datetime(2024, 1, 28, 6, 48, 0, 158710, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
