# Generated by Django 3.2.14 on 2024-01-28 08:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.CharField(default=datetime.datetime(2024, 1, 28, 8, 16, 32, 463031, tzinfo=utc), max_length=800),
            preserve_default=False,
        ),
    ]
