# Generated by Django 3.2.14 on 2024-01-29 08:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='BlogId',
            field=models.CharField(default=datetime.datetime(2024, 1, 29, 8, 36, 47, 656245, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
