# Generated by Django 3.2.14 on 2024-02-25 00:32

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1000)),
                ('description', tinymce.models.HTMLField()),
                ('image', models.CharField(max_length=400)),
            ],
        ),
    ]
