# Generated by Django 3.2.14 on 2024-02-25 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='image',
            new_name='Project_image',
        ),
    ]
