# Generated by Django 3.2.14 on 2024-03-10 00:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20240225_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='discription',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
